"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['__init__.py']
DATA_FILES = ['AppIcon.icns', 'resources/']
OPTIONS = {'iconfile':'AppIcon.icns'}

setup(
    name="TunesBar",
    version="0.1",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
